### ISSUE TITLE
`effector-logger` breaks operations' priorities

### ISSUE THREAD

**Issue by yumauri** [effector/logger#100]
Subj, `effector-logger` somehow breaks effector priorities, for example, `sample` began to work earlier, than `.on`, which completely breaks synchronous logic.

Code
```js
const passingBy = createEvent();
const goAhead = createEvent();
const $gate = createStore(true)
  .on(passingBy, () => false)
  .on(goAhead, () => true);

sample({
  clock: passingBy,
  target: goAhead
});

passingBy()
```
works differently, when you import from from `"effector-logger"`:
- with `import {} from "effector"` store `$gate` contains `true` after calculations
- with `import {} from "effector-logger"` store `$gate` contains `false` after calculations, because `sample` executes earlier, than `.on(passingBy`

Repo with reproduce: https://github.com/yumauri/effector-logger-issue

**Comment by ZothOmmog** [comment]
Same problem
https://codesandbox.io/s/effector-logger-break-89zdmc?file=/src/App.js

**Comment by zerobias** [comment]
Looks like an issue in [effector-inspector](https://codesandbox.io/s/effector-logger-break-forked-irfksd?file=/src/App.js)
If you set inspector option to true (which is a default) the issue occurs

**Comment by yumauri** [comment]
Yep, looks like. Might it be because inspector calls event inside of compute step?
https://github.com/effector/inspector/blob/master/src/index.ts#L235
