### ISSUE TITLE
Move effector-inspector to peer dependencies

### ISSUE THREAD

**Issue by k-egor-smirnov** [effector/logger#117]
In my project, I don't want to use `effector-inspector`, but it still installs and pulls a lot of unnecessary modules like `solid`.
I suggest to add `effector-inspector` to peer dependencies and install it by demand.

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
