### ISSUE TITLE
Option to allow disabling console logs

### ISSUE THREAD

**Issue by darianstlex** [effector/logger#16]
Hi, I really like effector and everything around it. Would it be possible to add config option to be able to disable console logs, let say I am using redux tool and to have also console logs seems redundant? Thanks

**Comment by Crysp** [comment]
just don't use logger 🙂

**Comment by darianstlex** [comment]
yeah, but I'd like to have logs in redux dev tool

**Comment by Crysp** [comment]
sorry, i didn't understand you. i thought you use redux-logger.

i don't know how redux tool works inside. but may be its based on console logs?

**Comment by sergeysova** [comment]
How it is works described here https://github.com/sergeysova/effector-logger/blob/master/src/redux-devtools.ts.

@darianstlex Thank you for your contribution, I am working on the solution now.

**Comment by darianstlex** [comment]
Thanks you

**Comment by sergeysova** [comment]
@darianstlex With [`v0.8.0`](https://github.com/effector/logger/releases/tag/v0.8.0) you can easily disable console logs:

```ts
import { createDomain } from 'effector'
import { attachLogger } from 'effector-logger/attach'

const app = createDomain()

// Only redux devtools enabled
attachLogger(app, { console: "disabled", inspector: "disabled" })
```
