### ISSUE TITLE
Do not show SyntheticEvent object 

### ISSUE THREAD

**Issue by popuguytheparrot** [effector/logger#17]
Hi. 

Сan replace SyntheticEvent with a string symbol because logging an entire SyntheticEvent object causes lags in the browser.

Current behavior:
![image](https://user-images.githubusercontent.com/19804652/85277842-b860e380-b48c-11ea-9cb9-7adfe6115052.png)

Expected: 
☄️effector `event` * → editRate('SyntheticEvent ')

**Comment by SQReder** [comment]
I think configure method can be expanded to adjust logging details for some units
Something like this:
```ts
const event = createEvent<HeavyPayload>()
configure(event, { payloadMap: heavyPayload => `HeavyPayload${heavyPayload.discriminator}` })
```
