### ISSUE TITLE
Optionally log combined and mapped stores

### ISSUE THREAD

**Issue by sergeysova** [effector/logger#2]
https://share.effector.dev/5x9KO6ZK

**Comment by sergeysova** [comment]
Idea from linked issue

> Maybe we could create an API for attaching logger to a particular derived store, which might look like this:
> 
> ```ts
> import { attachLogger } from 'effector-logger/attach';
> 
> const myComplextCombinedStore$ = combine(authState$, todos$, permissions$, combinator);
> attachLogger(myComplextCombinedStore, 'myComplextCombinedStore$');
> ```

**Comment by AlexandrHoroshih** [comment]
Added in the latest `0.14.0` release

https://github.com/effector/logger#force-any-unit-to-be-logged
