### ISSUE TITLE
Select data type for logging

### ISSUE THREAD

**Issue by ejnshtein** [effector/logger#23]
It will be nice to be able to choose what to log in the console and, mainly, in redux dev tools.
Like select only `stores` and `events` to be logged, otherwise, there's a lot of pollution by effects stores `pending` and `inFlight` in dev tools.

**Comment by sergeysova** [comment]
@ejnshtein You can use [effector-inspector](https://github.com/effector/inspector)

**Comment by sergeysova** [comment]
Also you can log only one file or domain

**Comment by sergeysova** [comment]
Or use filtration in devtools console
