### ISSUE TITLE
ReduxDevtools doesn't see effector-logger

### ISSUE THREAD

**Issue by bonkboykz** [effector/logger#26]
ReduxDevtools doesn't see attached effector-logger printing `No store found`.

I'm using NextJs and attaching the logger like this:
```js
if (!isServer) {
    const { attachLogger } = require('effector-logger/attach');

    attachLogger(rootDomain, { reduxDevtools: 'enabled', console: 'enabled' });
}
```

The `console.log` is working, though

**Comment by sergeysova** [comment]
Thank you for bug request.

Is it still actual and logger don’t showing in devtools?

**Comment by bonkboykz** [comment]
The issue has been resolved. Thank you!
