### ISSUE TITLE
Doesn't work with redux-devtools chrome extension

### ISSUE THREAD

**Issue by Dema** [effector/logger#27]
It gives an error

```
1.chunk.js:formatted:259960 TypeError: D.send is not a function
    at 1.chunk.js:formatted:140054
    at 1.chunk.js:formatted:140058
    at fe (1.chunk.js:formatted:142973)
```
D.send is ` reduxDevTools.send({`
As I understand, this line https://github.com/effector/logger/blob/master/src/redux-devtools.ts#L8 should look like 
```
typeof window !== "undefined" &&
window.__REDUX_DEVTOOLS_EXTENSION__.connect
  ? window.__REDUX_DEVTOOLS_EXTENSION__.connect()
  : window.__REDUX_DEVTOOLS_EXTENSION__;

```

If I try to debug, `D` is an object with just a `connect` function.

**Comment by sergeysova** [comment]
Thank you for bug request.

is error still throwing?

**Comment by sergeysova** [comment]
@Dema Have you used logger again?

**Comment by Dema** [comment]
Yeah.. FYI, the issue was not with redux-devtools, but with xstate devtools extension https://chrome.google.com/webstore/detail/xstate-devtools/aamnodipnlopbknpklfoabalmobheehc. It register itself similar to redux-devtools because xstate can broadcast its state as if it is a redux app.
