### ISSUE TITLE
Mute events from store

### ISSUE THREAD

**Issue by bonkboykz** [effector/logger#29]
Is there a way to mute events from one of the stores completely?

**Comment by sergeysova** [comment]
Thank you for question.
It isn’t possible right now.

please, explain why you need to mute events?

**Comment by bonkboykz** [comment]
Hi!

I'm using websockets, events are emitted on very frequent actions, like mouse moves, and they make looking for the particular event trigger in the console quite troublesome

**Comment by sergeysova** [comment]
`configure` released in https://github.com/effector/logger/releases/tag/v0.13.0

```ts
import { createEvent } from 'effector'
import { configure } from 'effector-logger'
import { $data, loadDataFx } from './model'

const pageMounted = createEvent<number>();

configure(pageMounted, { log: 'disabled' })

// You can pass multiple units as array
configure([$data, loadDataFx], { log: 'disabled' })
```
