### ISSUE TITLE
Can't setup logger

### ISSUE THREAD

**Issue by PFight** [effector/logger#31]
Please, clear out, what required steps to setup logger? Documentation says about:

-  babel-plugin (I do not use babel in project build). Therefore, I added plugin to storybook (wich uses babel) and nothing happens
- replacing imports (I do not want to modify my sources for dev/prod builds, and do not know, how to setup replace imports automaticly in rollup), 
- calling attach to domain (I have no single root domain, and do not want to place debug call in every component, and remove it in production build). I can't use effector-root, because of p.2.

When I just simple call createInspector() I receive empty inspector window. Ho to add my stores to this inspector?

     "effector": "^21.7.5",
    "effector-logger": "^0.9.0",
    "effector-react": "^21.2.1",

**Comment by PFight** [comment]
Got working by manually replacing imports... Not usable solution.

**Comment by PFight** [comment]
So, does it correct, that to setup logger I should do one of this:
- create global domain and call attach
- replace imports somehow

What do babel plugin there anyway?
I understand, that rollup is not popular bundler yet, but can someone provide example of replacing imports in webpack? May be I will get inspiration from this.

**Comment by sergeysova** [comment]
@PFight sorry for long answer.
Is question still actual?

**Comment by PFight** [comment]
Thanks, tell please, what do babel plugin? Replaces imports? I configured logger by replacing imports locally or globally, but, it looks like not very convinient way of debugging.

**Comment by sergeysova** [comment]
Babel plugin adds locations and names to units, to show it in devtools console.

In [v0.11] added babel-plugin bundler with logger, that automatically replaces imports of "effector" to "effector-logger"

[v0.11]: https://github.com/effector/logger/releases/tag/v0.11.0

**Comment by PFight** [comment]
Thanks!
