### ISSUE TITLE
[BUG] attachLogger and createInspector - Payloads too large and input handler took lot of time

### ISSUE THREAD

**Issue by lokhmakov** [effector/logger#33]
## When:

1. `git clone git@github.com:accesso-app/frontend.git`
2. attachLogger to root
3. createInspector after client initialization
4. Without createInspector there is no "Application state or actions payloads are too large" and input handlers reduce time consuming to 300ms 

## Current behavior:

1. Application state or actions payloads are too large making Redux DevTools serialization slow and consuming a lot of memory. See https://git.io/fpcP5 on how to configure it.
2. 'input' handler took more then 1000ms
3. This synthetic event is reused for performance reasons

## Expected behavior:

1. 'input' handler took less than 10ms without errors

## Environment:

- node vesrion: `v14.15.3`

## Screenshots:

<img width="718" alt="Screenshot 2021-02-26 at 10 32 00" src="https://user-images.githubusercontent.com/94939/109272275-b0c6bb00-7821-11eb-818d-95285cdc6e1d.png">

**Comment by sergeysova** [comment]
`configure` released in https://github.com/effector/logger/releases/tag/v0.13.0

```ts
import { createEvent } from 'effector'
import { configure } from 'effector-logger'
import { $data, loadDataFx } from './model'

const pageMounted = createEvent<number>();

configure(pageMounted, { log: 'disabled' })

// You can pass multiple units as array
configure([$data, loadDataFx], { log: 'disabled' })
```
