### ISSUE TITLE
Setting up logger with webpack and ts-loader

### ISSUE THREAD

**Issue by ierhyna** [effector/logger#43]
Hey,
I'm wondering if there is an easy way to use logger with webpack and ts-loader without replacing paths manually? I don't use babel-loader in my project.

**Comment by sergeysova** [comment]
On present no way to do it without babel-loader.
You will also need babel-loader to setup tests.

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

Also, logger does not require any plugins to work anymore.
Usage of "effector/babel-plugin" is still desirable though, as it provides useful metadata for the logs.

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
