### ISSUE TITLE
Logging of mapped/combined stores

### ISSUE THREAD

**Issue by val-o** [effector/logger#51]
In some cases, it would be nice to have mapped/combined stores to be logged as well. Although if we will log all of the derived stores it might add noise, if, for example, derived store is solely used as an argument for methods like `sample`, etc.

Maybe we could create an API for attaching logger to a particular derived store, which might look like this:

```ts

import { attachLogger } from 'effector-logger/attach';

const myComplextCombinedStore$ = combine(authState$, todos$, permissions$, combinator);
attachLogger(myComplextCombinedStore, 'myComplextCombinedStore$');

```

**Comment by sergeysova** [comment]
Looks like a duplicate for #2

**Comment by sergeysova** [comment]
@val-o Thank you for the issue. I pinned the original issue to lift up the discussion.
