### ISSUE TITLE
Getting JSON parse error when calling events with no parameters after upgrade

### ISSUE THREAD

**Issue by slikk66** [effector/logger#55]
**What is the current behavior:**
Hi, just upgraded to:
```json
        "effector": "^22.1.1",
        "effector-logger": "^0.12.1",
        "effector-react": "^22.0.4",
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

```ts
export const resetSurvey = createEvent();

export default createStore<surveyStore>(emptySurveyStore)
    .on(resetSurvey, (state) => {
        return {
            ...state,
        };
    })
```

**What is the expected behavior:**
With the above snippet, nothing should change.  However I'm getting a JSON parse error show in the console here:

```ts
$events
  .on(eventAdd, (map, payload) => ({
    ...map,
    [payload.name]: {
      mapped: payload.mapped,
      history: [],
    },
  }))
  .on(eventTriggered, (map, { name, params }) => {
    // should not change the order of fields

    map[name] = {
      ...map[name],
      history: [JSON.parse(JSON.stringify(params)), ...map[name].history],     <--- here
    };
    return { ...map };
  });
```
I'm guessing since the event has no params, it's trying to stringify/parse a null/undefined and that is causing the error.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
yea used to work, I just reverted back to these and not seeing the error again
```json
        "effector": "^21.8.5",
        "effector-logger": "^0.10.0",
        "effector-react": "^21.2.1",
```

**Comment by sergeysova** [comment]
@slikk66 Thank you for the issue report!

You use `export default` but the babel-plugin parses the name of the variable to set it to the store config. I strongly recommend using named exports for effector units, therefore the babel-plugin can recognize store names and display them in the list of stores of effector-inspector.

But the `export default` problem looks like a bug, but I don't know what name should be displayed for store exported as default, due it hasn't a name.

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.


This issue was also fixed in that release.

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
