### ISSUE TITLE
`effector-logger/attach` is not exist, only `/dist/attach` works

### ISSUE THREAD

**Issue by domosedov** [effector/logger#59]
```ts
import { attachLogger } from 'effector-logger/attach';
```

```log
Could not find a declaration file for module 'effector-logger/attach'. '/node_modules/effector-logger/attach.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/effector-logger` if it exists or add a new declaration (.d.ts) file containing `declare module 'effector-logger/attach';`ts(7016)
```

## Works as expected
```ts
import { attachLogger } from 'effector-logger/dist/attach';
```

## node
14.16.1

## typescript
4.4.3

## effector
22.1.1

## effector-logger
0.13.0

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

`/attach` was also deleted

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
