### ISSUE TITLE
effector/babel-plugin configuration doesn't work as expected

### ISSUE THREAD

**Issue by SQReder** [effector/logger#60]
If reactSsr flag is provided through the effector-logger babel plugin - it does nothing

```js
module.exports = {
  plugins: [['effector-logger/babel-plugin', { effector: { reactSsr: true } }]],
}
```

I've modified `node-modules/effector/babel-plugin.js` to see if rewrite actually happens
```js
// node-modules/effector/babel-plugin.js#242
      ...
      if (reactSsr) {
        if (source === 'effector-react' || source === 'effector-react/compat') {
          path.node.source.value = 'effector-react/scope'
          console.log(source, 'rewrited')
        }
      }
      ...
```
It logs if `effector/babel-plugin` used directly, but not for `effector-logger`

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

Logger's custom babel plugin was also deleted.

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
