### ISSUE TITLE
Any way to disable based on a flag/setting?

### ISSUE THREAD

**Issue by slikk66** [effector/logger#61]
Hi, this is probably a dumb question, but if I build to production and don't change `import { createEvent, createStore } from "effector-logger";` is there a way to turn it off using a flag or env var etc, or do I have to change the import?

Thanks!

**Comment by sergeysova** [comment]
You can use babel-plugin, like this:

```json
{
  "plugins": ["effector-logger/babel-plugin"]
}
```

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

With new update you can just import it conditionally

```ts
if (process.env.ENV === "development") {
 const { attachLogger } = await import("effector-logger")

 attachLogger(...)
  
}
```

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
