### ISSUE TITLE
Error: Error serializing `.initialState.bxdte["-2xkzew"].effect` returned from `getStaticProps` in "/catalog/[...slug]".

### ISSUE THREAD

**Issue by Rastraponovich** [effector/logger#64]
Когда используется effector-logger вместе с NextJs и effector22+, SSR\GSSP то,конфигурация babel заменяет импорты из 'effector' на "effector-logger" в следствии чего приложение падает из-за не соотвествия сериализации данных как я понял :\

"effector-logger": "^0.13.1",
        "effector": "^22.1.1",
        "effector-react": "^22.0.4",
        "next": "^12.0.4",

Если убрать из конфигурации babel "plugins": ["effector-logger/babel-plugin"], то все работает, но нет логов :(

прошу рассмотреть доработку.

**Comment by sergeysova** [comment]
@Rastraponovich можно не добавлять babelPlugin из effector-logger
а использовать root домен в нужных местах и цеплять логгер уже к нему

но в идеале, это повторить где-нибудь в репозитории указанное выше поведение, когда с плагином все ломается

**Comment by Rastraponovich** [comment]
тут [codesandbox ](https://codesandbox.io/s/long-snowflake-jzj5d/) коментим строку в babelrc все работает, раскоменчиваем не работает.

по поводу доменов, в effector 22 в форк больше не нужен домен. по этому я не совсем понимаю как это реализовать...

**Comment by zerobias** [comment]
Некст падает из-за попытки сериализации служебных сторов, им нужно добавить флаг serialize: ignore в реализации effector-inspector

**Comment by zerobias** [comment]
@sergeysova опубликуешь [апдейт инспектора](https://github.com/effector/inspector/commit/828f006cbc8be5f52311e7dd072cb8aeff259021)? тогда логгер исправится автоматически

**Comment by sergeysova** [comment]
@zerobias спасибо!

https://github.com/effector/inspector/releases/tag/v0.7.5

@Rastraponovich По идее, должно быть достаточно удалить и заново установить effector-logger

**Comment by Rastraponovich** [comment]
> @zerobias спасибо!
> 
> https://github.com/effector/inspector/releases/tag/v0.7.5
> 
> @Rastraponovich По идее, должно быть достаточно удалить и заново установить effector-logger

Спасибо большое в codesandbox работает.
