### ISSUE TITLE
Error: combine expects a store in a field clock

### ISSUE THREAD

**Issue by Rastraponovich** [effector/logger#65]
Добрый день! когда мы подключаем logger к NextJs + effector в ts получаем ошибку "Error: combine expects a store in a field clock" 

если из .babelrc убрать настройку logger то все работает и ошибки нет

[codesandbox.io](https://codesandbox.io/s/long-snowflake-jzj5d)

**Comment by sergeysova** [comment]
@Rastraponovich подскажи, какие у тебя версии эффектора, логгера и некст?

**Comment by Rastraponovich** [comment]
> 



> @Rastraponovich подскажи, какие у тебя версии эффектора, логгера и некст?

"effector": "22.1.2",
    "effector-logger": "0.13.1",
    "effector-react": "22.0.4",
    "next": "latest",
    "react": "17.0.2",
    "react-dom": "17.0.2",

**Comment by MichaelShipitsyn** [comment]
Repository to reproduce - https://github.com/MichaelShipitsyn/effector-nextjs

**Comment by Fyzu** [comment]
Same issue.

After add babel plugin, application throw error:
```
effector.mjs:1 Uncaught Error: combine expects a store in a field clock
    at r (effector.mjs:1)
    at effector.mjs:1
    at e (effector.mjs:1)
    at yt (effector.mjs:1)
    at p (effector.mjs:1)
    at xt (effector.mjs:1)
    at x (effector.mjs:1)
    at newModel (model.ts:69)
```

On code:
```ts
    const showSelected = createEvent()
    sample({ // line 69
        clock: showSelected,
        source: [$store1, $store2],
        target: $result,
        fn: ([state1, state2]) => ({ state1, state2 }),
    });
```

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

Logger's custom babel plugin was also deleted

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
