### ISSUE TITLE
Error: guard: expect clock to be a unit (store, event or effect) or array of units

### ISSUE THREAD

**Issue by kozlovzxc** [effector/logger#75]
Hey 👋  Not sure if I'm doing something wrong or there is actually a bug.

So I have this packages installed:
```
        "effector": "^21.8.11",
        "effector-react": "^21.3.2",
        "effector-logger": "^0.13.3",
```
And I'm using parcel v2 as a builder.

Every time I try to use anything related to `effector-logger` I get this error

![image](https://user-images.githubusercontent.com/6112517/150638395-7361c6fb-47b4-40e7-a252-4fb950751f3e.png)

I get this error either if I import bablel config or either just directly import something from 'effector-logger'.

Which other details can be useful?

**Comment by kozlovzxc** [comment]
Maybe it's related to https://github.com/effector/logger/issues/65

**Comment by AlexandrHoroshih** [comment]
Looks like a https://github.com/effector/effector/issues/601 🤔

**Comment by kozlovzxc** [comment]
Just noticed, that I have outdated effector version (v21 compared to latest v22), going to update and check if it still persists

**Comment by kozlovzxc** [comment]
Updated all packages to the latest versions, now there is this error 🤔 

![image](https://user-images.githubusercontent.com/6112517/150640702-2acf842f-99b4-4e23-ae0a-b05b519b3add.png)

**Comment by AlexandrHoroshih** [comment]
🤔 Could you try to clear cache of the bundler? Just in case

**Comment by kozlovzxc** [comment]
Looks like effector doesn't work with parcel itself 🤔  

Here is repo with just 2 packages - effector & parcel - https://github.com/kozlovzxc/parcel-effector-example/

![image](https://user-images.githubusercontent.com/6112517/150643574-117d823b-03f9-49d4-8977-1ce8552d7eb5.png)

And I'm using example from docs themselves

```
import {createEvent, createStore} from 'effector'

const addTodo = createEvent()
const clearTodoList = createEvent()

const $todos = createStore([])
  // Will update store when addTodo is fired
  .on(addTodo, (list, todo) => [...list, todo])
  // Will reset store to default state when clearTodos is fired
  .reset(clearTodoList)

// Log initial store value and each change
$todos.watch(todos => {
  console.log('todos', todos)
})
// => todos []

addTodo('go shopping')
// => todos ['go shopping']

addTodo('go to the gym')
// => todos ['go shopping', 'go to the gym']

clearTodoList()
// => todos []
```

@AlexandrHoroshih Should I open issue in effector main repo?

**Comment by kozlovzxc** [comment]
Just by downgrading version in this example, figure out that `v21.8.12` works and `v22.0.0` doesn't

**Comment by kozlovzxc** [comment]
Btw, maybe this is resolved issue, but maybe it relates to parcel somehow again. Looks like names are minified for `effector@21.8.12` & `effector-logger@0.11.0 ` 

![image](https://user-images.githubusercontent.com/6112517/150645239-11932464-a8c0-4d7f-b948-3e23d4cc106a.png)

**Comment by kozlovzxc** [comment]
Please let me know if I can help somehow or if you need any other details 🙏

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

Also, logger does not require any plugins to work anymore, so all related issues are gone too.
Usage of "effector/babel-plugin" is still desirable though, as it provides useful metadata for the logs.

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
