### ISSUE TITLE
Add option for non-babel users in readme

### ISSUE THREAD

**Issue by YanLobat** [effector/logger#89]
we need to show up how to use this debugging tool without having babel in project

**Comment by mfeitoza** [comment]
I could work in integration with Vite, probably I will need somo initial guidance.

**Comment by sergeysova** [comment]
Vite supports babel out of the box

**Comment by AlexandrHoroshih** [comment]
Hello!

As of the recent '0.14.0' release, 'effector-logger' no longer includes 'effector-inspector' and integration with redux-devtools, so all related issues are gone.

Also, logger does not require any plugins to work anymore.
Usage of "effector/babel-plugin" is still desirable though, as it provides useful metadata for the logs.

See the release notes for details
https://github.com/effector/logger/releases/tag/v0.14.0
